server:
  port: 443
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  plugins:
    # Replace VERSION with the current version as shown by the Releases tab or a long commit hash for snapshots.
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.2"
      repository: "https://maven.lavalink.dev/releases" 
  server:
    password: youshallpass
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 440
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    max-history: 9
    max-size: 300MB
  path: /app/logs/

  level:
    root: INFO
    lavalink: INFO
