server:
  port: 443
  address: kutsal-bot.up.railway.app
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: youshallpass
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 440
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    max-history: 9
    max-size: 300MB
  path: /app/logs/

  level:
    root: INFO
    lavalink: INFO
